sudo: false
language: node_js
cache:
  - "node_modules"
  install: npm install
notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7
  email: true
node_js:
  - '6'
  - '8'
  - '10'
before_script:
  - npm prune
